config/routes.rb
Projections::Application.routes.draw do
  root :to => 'static#home'

  resources :players do
    collection do
      get 'espn_scrap'
      get 'cbs_scrap'
      get 'nfl_scrap'

      get 'quarterbacks'
      get 'runningbacks'
      get 'widereceivers'
      get 'tightends'
      get 'defenses'
      get 'kickers'
      get :csv
    end
  end

end

app/models/player.rb
class Player < ActiveRecord::Base
  attr_accessible :attempts, :completions, :fpoints, :fumble_recoveries, :fumble_lost, :source, :interceptions, :kicking_attempts_1_to_39, :kicking_attempts_40_to_49, :kicking_attempts_XP, :kicking_attempts_over_50, :kicking_attempts_total, :kicking_completions_1_to_39, :kicking_completions_40_to_49, :kicking_completions_XP, :kicking_completions_over_50, :kicking_completions_total, :name, :pass_tds, :pass_yards, :two_pt_conversions, :picture_url, :points_against, :position, :receiving_tds, :receiving_yards, :receptions, :rush_tds, :rush_yards, :rushes, :sacks, :stat_year, :targets, :team, :yards_against, :fumble_forced, :safety

  	def nflDataPull(number_of_players = 100)
  		(1..number_of_players).step(25) do |i|			
			#QBs
			url = "http://fantasy.nfl.com/research/projections?position=1&statType=seasonProjectedStats&offset="+ i.to_s				
			nflPlayers(url)				
			#RBs
			url = "http://fantasy.nfl.com/research/projections?position=2&statType=seasonProjectedStats&offset="+ i.to_s				
			nflPlayers(url)				
			#WR
			url = "http://fantasy.nfl.com/research/projections?position=3&statType=seasonProjectedStats&offset="+ i.to_s				
			nflPlayers(url)			
			#TE
			url = "http://fantasy.nfl.com/research/projections?position=4&statType=seasonProjectedStats&offset="+ i.to_s				
			nflPlayers(url)			
			#K
			url = "http://fantasy.nfl.com/research/projections?position=7&statType=seasonProjectedStats&offset="+ i.to_s				
			nflKickers(url)			
			#DEF
			url = "http://fantasy.nfl.com/research/projections?position=8&statType=seasonProjectedStats&offset="+ i.to_s				
			nflDefenses(url)			
		end  			
  	end
  	def nflDefenses(url)
  		doc = getWebsiteAsNokogiriDoc(url)
  		doc = doc.css(".odd") + doc.css(".even")
  		doc.each do |nflPlayer|
  			player = Player.new

		 	player.source = "NFL"
		 	player.stat_year = 2014

  		 	player.name = nflPlayer.css(".playerName").text
  			player.team = nflPlayer.css("em").text.split(" - ")[1]
   		 	player.position = "D/ST"

		    player.sacks = nflPlayer.css(".statId-45").text
		    player.interceptions = nflPlayer.css(".statId-46").text
		    player.fumble_recoveries = nflPlayer.css(".statId-47").text
		    player.safety = nflPlayer.css(".statId-49").text
		    player.rush_tds = nflPlayer.css(".statId-50").text
		    player.points_against = nflPlayer.css(".statId-54").text

			player.fpoints = nflPlayer.css("td.last").text

	  		player.save
  		end
  	end
  	def nflKickers(url)
  		doc = getWebsiteAsNokogiriDoc(url)
  		doc = doc.css(".odd") + doc.css(".even")
  		doc.each do |nflPlayer|
  			player = Player.new

		 	player.source = "NFL"
		 	player.stat_year = 2014

  		 	player.name = nflPlayer.css(".playerName").text
  			player.team = nflPlayer.css("em").text.split(" - ")[1]
   		 	player.position = nflPlayer.css("em").text.split(" - ")[0]

		    player.kicking_completions_XP = nflPlayer.css(".statId-33").text
		    player.kicking_completions_1_to_39 = nflPlayer.css(".statId-35").text.to_i + nflPlayer.css(".statId-36").text.to_i + nflPlayer.css(".statId-37").text.to_i
		    player.kicking_completions_40_to_49 = nflPlayer.css(".statId-38").text
		    player.kicking_completions_over_50 = nflPlayer.css(".statId-39").text

			player.fpoints = nflPlayer.css("td.last").text

	  		player.save
  		end
  	end
  	def nflPlayers(url)
  		doc = getWebsiteAsNokogiriDoc(url)
  		doc = doc.css(".odd") + doc.css(".even")
  		doc.each do |nflPlayer|
  			player = Player.new

		 	player.source = "NFL"
		 	player.stat_year = 2014

  		 	player.name = nflPlayer.css(".playerName").text
  			player.team = nflPlayer.css("em").text.split(" - ")[1]
   		 	player.position = nflPlayer.css("em").text.split(" - ")[0]

		    player.pass_yards = nflPlayer.css(".statId-5").text
		    player.pass_tds = nflPlayer.css(".statId-6").text
		    player.interceptions = nflPlayer.css(".statId-7").text

		    player.rush_yards = nflPlayer.css(".statId-14").text
		    player.rush_tds = nflPlayer.css(".statId-15").text

		    player.receiving_yards = nflPlayer.css(".statId-21").text
		    player.receiving_tds = nflPlayer.css(".statId-22").text

		    player.forced_fumble = nflPlayer.css(".statId-29").text
		    player.two_pt_conversions = nflPlayer.css(".statId-32").text

		    player.fumble_lost = nflPlayer.css(".statId-30").text
			player.fpoints = nflPlayer.css("td.last").text

	  		player.save
  		end
  	end

  	def cbsDataPull
		##### CBS Average
  		url = "http://fantasynews.cbssports.com/fantasyfootball/stats/weeklyprojections/QB/season/avg/standard?&print_rows=9999"
  		cbsQuarterbacks(url)
   		url = "http://fantasynews.cbssports.com/fantasyfootball/stats/weeklyprojections/RB/season/avg/standard?&print_rows=9999"
  		cbsRunningBacks(url)
  		url = "http://fantasynews.cbssports.com/fantasyfootball/stats/weeklyprojections/WR/season/avg/standard?&print_rows=9999"
  		cbsWideReceivers(url, "WR")
   		url = "http://fantasynews.cbssports.com/fantasyfootball/stats/weeklyprojections/TE/season/avg/standard?&print_rows=9999"
  		cbsWideReceivers(url, "TE")
   		url = "http://fantasynews.cbssports.com/fantasyfootball/stats/weeklyprojections/K/season/avg/standard"
  		cbsKickers(url)
   		url = "http://fantasynews.cbssports.com/fantasyfootball/stats/weeklyprojections/DST/season/avg/standard"
  		cbsDefenses(url)

		##### Jamey Eisenberg
  		url = "http://fantasynews.cbssports.com/fantasyfootball/stats/weeklyprojections/QB/season/jamey_eisenberg/standard?&print_rows=9999"
  		cbsQuarterbacks(url, "Jamey Eisenberg")
   		url = "http://fantasynews.cbssports.com/fantasyfootball/stats/weeklyprojections/RB/season/jamey_eisenberg/standard?&print_rows=9999"
  		cbsRunningBacks(url, "Jamey Eisenberg")
  		url = "http://fantasynews.cbssports.com/fantasyfootball/stats/weeklyprojections/WR/season/jamey_eisenberg/standard?&print_rows=9999"
  		cbsWideReceivers(url, "WR", "Jamey Eisenberg")
   		url = "http://fantasynews.cbssports.com/fantasyfootball/stats/weeklyprojections/TE/season/jamey_eisenberg/standard?&print_rows=9999"
  		cbsWideReceivers(url, "TE", "Jamey Eisenberg")
   		url = "http://fantasynews.cbssports.com/fantasyfootball/stats/weeklyprojections/K/season/jamey_eisenberg/standard"
  		cbsKickers(url, "Jamey Eisenberg")
   		url = "http://fantasynews.cbssports.com/fantasyfootball/stats/weeklyprojections/DST/season/jamey_eisenberg/standard"
  		cbsDefenses(url, "Jamey Eisenberg")

		##### Dave Richard
  		url = "http://fantasynews.cbssports.com/fantasyfootball/stats/weeklyprojections/QB/season/dave_richard/standard?&print_rows=9999"
  		cbsQuarterbacks(url, "Dave Richard")
   		url = "http://fantasynews.cbssports.com/fantasyfootball/stats/weeklyprojections/RB/season/dave_richard/standard?&print_rows=9999"
  		cbsRunningBacks(url, "Dave Richard")
  		url = "http://fantasynews.cbssports.com/fantasyfootball/stats/weeklyprojections/WR/season/dave_richard/standard?&print_rows=9999"
  		cbsWideReceivers(url, "WR", "Dave Richard")
   		url = "http://fantasynews.cbssports.com/fantasyfootball/stats/weeklyprojections/TE/season/dave_richard/standard?&print_rows=9999"
  		cbsWideReceivers(url, "TE", "Dave Richard")
   		url = "http://fantasynews.cbssports.com/fantasyfootball/stats/weeklyprojections/K/season/dave_richard/standard"
  		cbsKickers(url, "Dave Richard")
   		url = "http://fantasynews.cbssports.com/fantasyfootball/stats/weeklyprojections/DST/season/dave_richard/standard"
  		cbsDefenses(url, "Dave Richard")
  	end
  	def cbsQuarterbacks(url, source = "CBS")
  		doc = getWebsiteAsNokogiriDoc(url)
  		doc = doc.css(".row1") + doc.css(".row2")
  		doc.shift
  		doc.each do |cbsPlayer|
  			player = Player.new
  			playerStats = cbsPlayer.css("td")
  		 	player.name = playerStats[0].text.split(/,/)[0].strip
  			player.team = playerStats[0].text.split(/,/)[1].to_s.strip
  		 	player.position = "QB"
		 	player.source = source
		 	player.stat_year = 2014

		    player.attempts = playerStats[1].text
		    player.completions = playerStats[2].text
		    player.pass_yards = playerStats[3].text
		    player.pass_tds = playerStats[4].text
		    player.interceptions = playerStats[5].text

		    player.rushes = playerStats[8].text
		    player.rush_yards = playerStats[9].text
		    player.rush_tds = playerStats[11].text
		    player.fumble_lost = playerStats[12].text
			player.fpoints = playerStats[13].text

	  		player.save

  		end
  	end
  	def cbsRunningBacks(url, source = "CBS")
  		doc = getWebsiteAsNokogiriDoc(url)
  		doc = doc.css(".row1") + doc.css(".row2")
  		doc.shift
  		players = Array.new
  		doc.each do |cbsPlayer|
  			playerStats = cbsPlayer.css("td")
  		 	player.name = playerStats[0].text.split(/,/)[0].strip
  			player.team = playerStats[0].text.split(/,/)[1].to_s.strip
  		 	player.position = "RB"
		 	player.source = source
		 	player.stat_year = 2014

		    player.rushes = playerStats[1].text
		    player.rush_yards = playerStats[2].text
		    player.rush_tds = playerStats[4].text
		    player.receptions = playerStats[5].text
		    player.receiving_yards = playerStats[6].text
		    player.receiving_tds = playerStats[8].text
		    player.fumble_lost = playerStats[9].text
		    player.fpoints = playerStats[10].text

	  		player.save
  		end
  	end
  	def cbsWideReceivers(url, position, source = "CBS")
  		doc = getWebsiteAsNokogiriDoc(url)
  		doc = doc.css(".row1") + doc.css(".row2")
  		doc.shift
  		doc.each do |cbsPlayer|
  			player = Player.new
  			playerStats = cbsPlayer.css("td")
  		 	player.name = playerStats[0].text.split(/,/)[0].strip
  			player.team = playerStats[0].text.split(/,/)[1].to_s.strip
  		 	player.position = position
		 	player.source = source
		 	player.stat_year = 2014

		    player.receptions = playerStats[1].text
		    player.receiving_yards = playerStats[2].text
		    player.receiving_tds = playerStats[4].text
		    player.fumble_lost = playerStats[5].text
			player.fpoints = playerStats[6].text

	  		player.save

  		end
  	end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # GET /players
  # GET /players.json
  def index
    source = params[:source]
    if source == "ALL"
      @players = Player.order('fpoints desc')
    else
      @players = Player.where(source: params[:source], stat_year: params[:year]).order('fpoints desc')
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
      format.csv { 
        send_data(
          Player.to_csv(@players),
          :type => 'application/excel',
          :filename => 'players.csv',
          :disposition => 'attachment'
        ) 
      }
    end
  end
  def quarterbacks
    source = params[:source]
    if source == "ALL"
      @players = Player.where(position: 'QB').order('fpoints desc')
    else
      @players = Player.where(source: params[:source], position: 'QB', stat_year: params[:year]).order('fpoints desc')
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
      format.csv { 
        send_data(
          Player.to_csv(@players),
          :type => 'application/excel',
          :filename => 'players.csv',
          :disposition => 'attachment'
        ) 
      }
    end
  end
  def runningbacks
    source = params[:source]
    if source == "ALL"
      @players = Player.where(position: 'RB').order('fpoints desc')
    else
      @players = Player.where(source: params[:source], position: 'RB', stat_year: params[:year]).order('fpoints desc')
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
      format.csv { 
        send_data(
          Player.to_csv(@players),
          :type => 'application/excel',
          :filename => 'players.csv',
          :disposition => 'attachment'
        ) 
      }
    end
  end
  def widereceivers
    source = params[:source]
    if source == "ALL"
      @players = Player.where(position: 'WR').order('fpoints desc')
    else
      @players = Player.where(source: params[:source], position: 'WR', stat_year: params[:year]).order('fpoints desc')
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
      format.csv { 
        send_data(
          Player.to_csv(@players),
          :type => 'application/excel',
          :filename => 'players.csv',
          :disposition => 'attachment'
        ) 
      }
    end
  end
  def tightends
    source = params[:source]
    if source == "ALL"
      @players = Player.where(position: 'TE').order('fpoints desc')
    else
      @players = Player.where(source: params[:source], position: 'TE', stat_year: params[:year]).order('fpoints desc')
    end    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
      format.csv { 
        send_data(
          Player.to_csv(@players),
          :type => 'application/excel',
          :filename => 'players.csv',
          :disposition => 'attachment'
        ) 
      }
    end
  end
  def defenses
    source = params[:source]
    if source == "ALL"
      @players = Player.where(position: 'D/ST').order('fpoints desc')
    else
      @players = Player.where(source: params[:source], position: 'D/ST', stat_year: params[:year]).order('fpoints desc')
    end   
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
      format.csv { 
        send_data(
          Player.to_csv(@players),
          :type => 'application/excel',
          :filename => 'players.csv',
          :disposition => 'attachment'
        ) 
      }
    end
  end
  def kickers
    source = params[:source]
    if source == "ALL"
      @players = Player.where(position: 'K').order('fpoints desc')
    else
      @players = Player.where(source: params[:source], position: 'K', stat_year: params[:year]).order('fpoints desc')
    end   
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
      format.csv { 
        send_data(
          Player.to_csv(@players),
          :type => 'application/excel',
          :filename => 'players.csv',
          :disposition => 'attachment'
        ) 
      }
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @player = Player.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/new
  # GET /players/new.json
  def new
    @player = Player.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(params[:player])

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render json: @player, status: :created, location: @player }
      else
        format.html { render action: "new" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.json
  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end

  # scrappers
  def espn_scrap
    Player.where(source: "ESPN").delete_all
    player = Player.new
    player.espnDataPull
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'ESPN Players successfully imported' }
    end
  end
  def cbs_scrap
    Player.where(:source => ['CBS', 'Jamey Eisenberg', 'Dave Richard']).delete_all
    player = Player.new
    @players = player.cbsDataPull
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'CBS Players successfully imported' }
    end
  end
  def nfl_scrap
    Player.where(source: 'NFL').delete_all
    player = Player.new
    @players = player.nflDataPull
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'NFL Players successfully imported' }
    end
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/defenses.html.erb
<% 
  model_class = Player 
  source = params[:source]
  year = params[:year]
%>

<div class="page-header">
  <h1>
    <%= link_to "Defenses", defenses_players_path(source: source, year: year, format: "csv") %>
    <small>Year: <%= year %> Source: <%= source %></small>
  </h1>
</div>
<%= link_to "<i class='icon-white icon-backward'></i> Home".html_safe, root_path, :class => 'btn btn-mini btn-primary' %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Team</th>
      <th>TDs</th>
      <th>Interceptions</th>
      <th>Sacks</th>
      <th>Forced Fumbles</th>
      <th>Fumble Recoveries</th>
      <th>Safety</th>
      <th>Points Against</th>
      <th>Yards Against</th>
      <th>Points</th>
    </tr>
  </thead>
  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.rush_tds %></td>
        <td><%= player.interceptions %></td>
        <td><%= player.sacks %></td>
        <td><%= player.forced_fumble %></td>
        <td><%= player.fumble_recoveries %></td>
        <td><%= player.safety %></td>
        <td><%= player.points_against %></td>
        <td><%= player.yards_against %></td>
        <td><%= player.fpoints %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/players/edit.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/players/index.html.erb
<% 
  model_class = Player 
  source = params[:source]
  year = params[:year]
%>

<div class="page-header">
  <h1><%= link_to "All Positions", players_path(source: source, year: year, format: "csv") %>, Year: <%= year %> Source: <%= source %></h1>
</div><%= link_to "<i class='icon-white icon-backward'></i> Home".html_safe, root_path, :class => 'btn btn-mini btn-primary' %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Source</th>
      <th>Year</th>
      <th>Name</th>
      <th>Position</th>
      <th>Team</th>
      <th>Rushes</th>
      <th>Rush Yards</th>
      <th>Rush TDs</th>
      <th>Targets</th>
      <th>Receptions</th>
      <th>Receiving Yards</th>
      <th>Receiving TDs</th>
      <th>Completions</th>
      <th>Attempts</th>
      <th>Pass Yards</th>
      <th>Pass TDs</th>
      <th>Interceptions</th>
      <th>Sacks</th>
      <th>Fumble Recoveries</th>
      <th>Points Against</th>
      <th>Yards Against</th>
      <th>Kicking Attempts 1 to 39</th>
      <th>Kicking Completions 1 to 39</th>
      <th>Kicking Attempts 40 to 49</th>
      <th>Kicking Completions 40 to 49</th>
      <th>Kicking Attempts Over 50</th>
      <th>Kicking Completions Over 50</th>
      <th>Kicking Total Attempts</th>
      <th>Kicking Total Completions</th>
      <th>Kicking Attempts XP</th>
      <th>Kicking Completions XP</th>
      <th>Fumble Lost</th>
      <th>Points</th>
    </tr>
  </thead>
  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.source %></td>
        <td><%= player.stat_year %></td>
        <td><%= player.name %></td>
        <td><%= player.position %></td>
        <td><%= player.team %></td>
        <td><%= player.rushes %></td>
        <td><%= player.rush_yards %></td>
        <td><%= player.rush_tds %></td>
        <td><%= player.targets %></td>
        <td><%= player.receptions %></td>
        <td><%= player.receiving_yards %></td>
        <td><%= player.receiving_tds %></td>
        <td><%= player.completions %></td>
        <td><%= player.attempts %></td>
        <td><%= player.pass_yards %></td>
        <td><%= player.pass_tds %></td>
        <td><%= player.interceptions %></td>
        <td><%= player.sacks %></td>
        <td><%= player.fumble_recoveries %></td>
        <td><%= player.points_against %></td>
        <td><%= player.yards_against %></td>
        <td><%= player.kicking_attempts_1_to_39 %></td>
        <td><%= player.kicking_completions_1_to_39 %></td>
        <td><%= player.kicking_attempts_40_to_49 %></td>
        <td><%= player.kicking_completions_40_to_49 %></td>
        <td><%= player.kicking_attempts_over_50 %></td>
        <td><%= player.kicking_completions_over_50 %></td>
        <td><%= player.kicking_attempts_total %></td>
        <td><%= player.kicking_completions_total %></td>
        <td><%= player.kicking_attempts_XP %></td>
        <td><%= player.kicking_completions_XP %></td>
        <td><%= player.fumble_lost %></td>
        <td><%= player.fpoints %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/players/kickers.html.erb
<% 
  model_class = Player 
  source = params[:source]
  year = params[:year]
%>

<div class="page-header">
  <h1>
    <%= link_to "Kickers", kickers_players_path(source: source, year: year, format: "csv") %>
    <small>Year: <%= year %> Source: <%= source %></small>
  </h1>
</div>
<%= link_to "<i class='icon-white icon-backward'></i> Home".html_safe, root_path, :class => 'btn btn-mini btn-primary' %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Team</th>
      <th>Kicking Attempts 1 to 39</th>
      <th>Kicking Completions 1 to 39</th>
      <th>Kicking Attempts 40 to 49</th>
      <th>Kicking Completions 40 to 49</th>
      <th>Kicking Attempts Over 50</th>
      <th>Kicking Completions Over 50</th>
      <th>Kicking Total Attempts</th>
      <th>Kicking Total Completions</th>
      <th>Kicking Attempts XP</th>
      <th>Kicking Completions XP</th>
      <th>Points</th>
    </tr>
  </thead>
  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.team %></td>
        <td><%= player.kicking_attempts_1_to_39 %></td>
        <td><%= player.kicking_completions_1_to_39 %></td>
        <td><%= player.kicking_attempts_40_to_49 %></td>
        <td><%= player.kicking_completions_40_to_49 %></td>
        <td><%= player.kicking_attempts_over_50 %></td>
        <td><%= player.kicking_completions_over_50 %></td>
        <td><%= player.kicking_attempts_total %></td>
        <td><%= player.kicking_completions_total %></td>
        <td><%= player.kicking_attempts_XP %></td>
        <td><%= player.kicking_completions_XP %></td>
        <td><%= player.fpoints %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/players/new.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/players/quarterbacks.html.erb
<% 
  model_class = Player 
  source = params[:source]
  year = params[:year]
%>

<div class="page-header">
  <h1>
    <%= link_to "Quarterbacks", quarterbacks_players_path(source: source, year: year, format: "csv") %>
    <small>Year: <%= year %> Source: <%= source %></small>
  </h1>
</div>
<%= link_to "<i class='icon-white icon-backward'></i> Home".html_safe, root_path, :class => 'btn btn-mini btn-primary' %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Team</th>
      <th>Rushes</th>
      <th>Rush Yards</th>
      <th>Rush TDs</th>
      <th>Completions</th>
      <th>Attempts</th>
      <th>Pass Yards</th>
      <th>Pass TDs</th>
      <th>Interceptions</th>
      <th>Fumble Lost</th>
      <th>Points</th>
    </tr>
  </thead>
  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.team %></td>
        <td><%= player.rushes %></td>
        <td><%= player.rush_yards %></td>
        <td><%= player.rush_tds %></td>
        <td><%= player.completions %></td>
        <td><%= player.attempts %></td>
        <td><%= player.pass_yards %></td>
        <td><%= player.pass_tds %></td>
        <td><%= player.interceptions %></td>
        <td><%= player.fumble_lost %></td>
        <td><%= player.fpoints %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/players/runningbacks.html.erb
<% 
  model_class = Player 
  source = params[:source]
  year = params[:year]
%>

<div class="page-header">
  <h1>
    <%= link_to "Running Backs", runningbacks_players_path(source: source, year: year, format: "csv") %>
    <small>Year: <%= year %> Source: <%= source %></small>
  </h1>
</div>
<%= link_to "<i class='icon-white icon-backward'></i> Home".html_safe, root_path, :class => 'btn btn-mini btn-primary' %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Team</th>
      <th>Rushes</th>
      <th>Rush Yards</th>
      <th>Rush TDs</th>
      <th>Receptions</th>
      <th>Receiving Yards</th>
      <th>ReceivingTDs</th>
      <th>Fumbles Lost</th>
      <th>Points</th>
    </tr>
  </thead>
  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.team %></td>
        <td><%= player.rushes %></td>
        <td><%= player.rush_yards %></td>
        <td><%= player.rush_tds %></td>
        <td><%= player.receptions %></td>
        <td><%= player.receiving_yards %></td>
        <td><%= player.receiving_tds %></td>
        <td><%= player.fumble_lost %></td>
        <td><%= player.fpoints %></td>
      </tr>
    <% end %>
  </tbody>
</table>